# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/new/seg_7.v
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/imports/new/s_74ls138l.v
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/imports/new/s_74ls138.v
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/imports/new/swich_1.v
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/imports/new/swich.v
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/imports/new/ctc.v
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/imports/new/clock_div.v
  D:/Xilinx_workspace/formal_assignment/formal_assignment.srcs/sources_1/imports/sources_1/imports/new/led_light.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx_workspace/formal_assignment/formal_assignment.data/wt [current_project]
set_property parent.project_dir D:/Xilinx_workspace/formal_assignment [current_project]
synth_design -top led_light -part xc7a100tcsg324-1
write_checkpoint led_light.dcp
report_utilization -file led_light_utilization_synth.rpt -pb led_light_utilization_synth.pb
